%YAML:1.0
aruco_bc_nmarkers: 4
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:218, corners:[ [ -110., -110., 0. ], [ -10., -110., 0. ], [
       -10., -10., 0. ], [ -110., -10., 0. ] ] }
   - { id:684, corners:[ [ 10., -110., 0. ], [ 110., -110., 0. ], [ 110.,
       -10., 0. ], [ 10., -10., 0. ] ] }
   - { id:1005, corners:[ [ -110., 10., 0. ], [ -10., 10., 0. ], [ -10.,
       110., 0. ], [ -110., 110., 0. ] ] }
   - { id:962, corners:[ [ 10., 10., 0. ], [ 110., 10., 0. ], [ 110.,
       110., 0. ], [ 10., 110., 0. ] ] }
