%YAML:1.0
aruco_bc_nmarkers: 35
aruco_bc_mInfoType: 0
aruco_bc_markers:
   - { id:835, corners:[ [ -290., -410., 0. ], [ -190., -410., 0. ], [
       -190., -310., 0. ], [ -290., -310., 0. ] ] }
   - { id:957, corners:[ [ -170., -410., 0. ], [ -70., -410., 0. ], [
       -70., -310., 0. ], [ -170., -310., 0. ] ] }
   - { id:123, corners:[ [ -50., -410., 0. ], [ 50., -410., 0. ], [ 50.,
       -310., 0. ], [ -50., -310., 0. ] ] }
   - { id:422, corners:[ [ 70., -410., 0. ], [ 170., -410., 0. ], [ 170.,
       -310., 0. ], [ 70., -310., 0. ] ] }
   - { id:500, corners:[ [ 190., -410., 0. ], [ 290., -410., 0. ], [
       290., -310., 0. ], [ 190., -310., 0. ] ] }
   - { id:632, corners:[ [ -290., -290., 0. ], [ -190., -290., 0. ], [
       -190., -190., 0. ], [ -290., -190., 0. ] ] }
   - { id:843, corners:[ [ -170., -290., 0. ], [ -70., -290., 0. ], [
       -70., -190., 0. ], [ -170., -190., 0. ] ] }
   - { id:2, corners:[ [ -50., -290., 0. ], [ 50., -290., 0. ], [ 50.,
       -190., 0. ], [ -50., -190., 0. ] ] }
   - { id:913, corners:[ [ 70., -290., 0. ], [ 170., -290., 0. ], [ 170.,
       -190., 0. ], [ 70., -190., 0. ] ] }
   - { id:809, corners:[ [ 190., -290., 0. ], [ 290., -290., 0. ], [
       290., -190., 0. ], [ 190., -190., 0. ] ] }
   - { id:417, corners:[ [ -290., -170., 0. ], [ -190., -170., 0. ], [
       -190., -70., 0. ], [ -290., -70., 0. ] ] }
   - { id:635, corners:[ [ -170., -170., 0. ], [ -70., -170., 0. ], [
       -70., -70., 0. ], [ -170., -70., 0. ] ] }
   - { id:514, corners:[ [ -50., -170., 0. ], [ 50., -170., 0. ], [ 50.,
       -70., 0. ], [ -50., -70., 0. ] ] }
   - { id:265, corners:[ [ 70., -170., 0. ], [ 170., -170., 0. ], [ 170.,
       -70., 0. ], [ 70., -70., 0. ] ] }
   - { id:545, corners:[ [ 190., -170., 0. ], [ 290., -170., 0. ], [
       290., -70., 0. ], [ 190., -70., 0. ] ] }
   - { id:507, corners:[ [ -290., -50., 0. ], [ -190., -50., 0. ], [
       -190., 50., 0. ], [ -290., 50., 0. ] ] }
   - { id:450, corners:[ [ -170., -50., 0. ], [ -70., -50., 0. ], [ -70.,
       50., 0. ], [ -170., 50., 0. ] ] }
   - { id:618, corners:[ [ -50., -50., 0. ], [ 50., -50., 0. ], [ 50.,
       50., 0. ], [ -50., 50., 0. ] ] }
   - { id:378, corners:[ [ 70., -50., 0. ], [ 170., -50., 0. ], [ 170.,
       50., 0. ], [ 70., 50., 0. ] ] }
   - { id:228, corners:[ [ 190., -50., 0. ], [ 290., -50., 0. ], [ 290.,
       50., 0. ], [ 190., 50., 0. ] ] }
   - { id:803, corners:[ [ -290., 70., 0. ], [ -190., 70., 0. ], [ -190.,
       170., 0. ], [ -290., 170., 0. ] ] }
   - { id:534, corners:[ [ -170., 70., 0. ], [ -70., 70., 0. ], [ -70.,
       170., 0. ], [ -170., 170., 0. ] ] }
   - { id:389, corners:[ [ -50., 70., 0. ], [ 50., 70., 0. ], [ 50.,
       170., 0. ], [ -50., 170., 0. ] ] }
   - { id:172, corners:[ [ 70., 70., 0. ], [ 170., 70., 0. ], [ 170.,
       170., 0. ], [ 70., 170., 0. ] ] }
   - { id:883, corners:[ [ 190., 70., 0. ], [ 290., 70., 0. ], [ 290.,
       170., 0. ], [ 190., 170., 0. ] ] }
   - { id:201, corners:[ [ -290., 190., 0. ], [ -190., 190., 0. ], [
       -190., 290., 0. ], [ -290., 290., 0. ] ] }
   - { id:121, corners:[ [ -170., 190., 0. ], [ -70., 190., 0. ], [ -70.,
       290., 0. ], [ -170., 290., 0. ] ] }
   - { id:475, corners:[ [ -50., 190., 0. ], [ 50., 190., 0. ], [ 50.,
       290., 0. ], [ -50., 290., 0. ] ] }
   - { id:615, corners:[ [ 70., 190., 0. ], [ 170., 190., 0. ], [ 170.,
       290., 0. ], [ 70., 290., 0. ] ] }
   - { id:584, corners:[ [ 190., 190., 0. ], [ 290., 190., 0. ], [ 290.,
       290., 0. ], [ 190., 290., 0. ] ] }
   - { id:257, corners:[ [ -290., 310., 0. ], [ -190., 310., 0. ], [
       -190., 410., 0. ], [ -290., 410., 0. ] ] }
   - { id:773, corners:[ [ -170., 310., 0. ], [ -70., 310., 0. ], [ -70.,
       410., 0. ], [ -170., 410., 0. ] ] }
   - { id:413, corners:[ [ -50., 310., 0. ], [ 50., 310., 0. ], [ 50.,
       410., 0. ], [ -50., 410., 0. ] ] }
   - { id:38, corners:[ [ 70., 310., 0. ], [ 170., 310., 0. ], [ 170.,
       410., 0. ], [ 70., 410., 0. ] ] }
   - { id:824, corners:[ [ 190., 310., 0. ], [ 290., 310., 0. ], [ 290.,
       410., 0. ], [ 190., 410., 0. ] ] }
